version: "3.0"

services:
  battleship-base:
    image: battleship-base
#    ports:
#      - "8080:8080"
    container_name: battleship-base-container
    tty: true
    stdin_open: true
#    working_dir: /app

  persistence:
    image: persistence
    volumes:
      - persistence-volume:/app
    ports:
      - "8081:8081"
    container_name: persistence-container
    tty: true
#    working_dir: /app

volumes:
  persistence-volume: