version: "3.9"

services:
  persistence:
    image: controller-image
    ports:
      - "8081:8080"
    container_name: controller-container
    tty: true
#    networks:
#      - my_network
#    working_dir: /fileio
#    volumes:
#      - ./:/fileio:xro