version: "2.1"

services:
#  battleship-base:
#    image: ghcr.io/mindwork-apps/battleship-base:1.0
#    ports:
#      - "8080:8080"
#    container_name: battleship-base-container
#    tty: true
#    stdin_open: true
#
#  persistence:
#    image: ghcr.io/mindwork-apps/persistence:1.1
#    volumes:
#      - persistence-volume:/app
#    ports:
#      - "8081:8081"
#    container_name: persistence-container
#    tty: true
#    environment:
#      MYSQL_USER: postgres
#      MYSQL_PASSWORD: 123
#      MYSQL_PORT: 5432
#      MYSQL_HOST: slick
#      MONGO_ROOT_USERNAME: root
#      MONGO_ROOT_PASSWORD: 123
#      MONGO_PORT: 27017
#      MONGO_HOST: mongo
#
#  slick:
#    image: postgres:16.3
#    restart: always
#    container_name: slick
#    environment:
#      POSTGRES_PASSWORD: 123
#      POSTGRES_USER: postgres
#      POSTGRES_HOST: slick
#      POSTGRES_PORT: 5432
#    ports:
#      - "5432:5432"
#  mongo:
#    image: mongo:7.0.9
#    restart: always
#    container_name: mongo
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: 123


  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1
#
#volumes:
#  persistence-volume: