name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Variables
      run: echo "TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Docker build
      run: docker build . --file Dockerfile --tag julianboehne/battleship:battleship_$TAG
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PW }}
    - name: Docker deploy
      run: docker push julianboehne/battleship:battleship_$TAG


