name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy Image to Docker-Hub
      run: 
        docker build . --file Dockerfile --tag battleship-game:$(date +%s)
        docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PW }}
        docker push julianboehne/battleship:$(date +%s)
